language:
    - cpp

install:
    # install cmake 2.8.10 manually, see
    #     * https://github.com/travis-ci-tester/travis-test-cmake
    - wget http://www.cmake.org/files/v2.8/cmake-2.8.10.tar.gz
    - tar xf cmake-2.8.10.tar.gz
    - cd cmake-2.8.10
    - sudo apt-get install libcurl3-dev
    - ./bootstrap --system-curl
    - make
    - sudo make install
    - cd ..
    # -- end

script:
    - mkdir _builds
    - cd _builds
    # download all
    - cmake ..
    # if run generate again, no download needed
    - cmake ..
