language:
    - cpp

install:
    - sudo apt-get install cmake
    - sudo apt-get install libcurl3-dev
    # install cmake toolchains and script
    - POLLY_VERSION="0.4.4"
    - wget "https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz"
    - tar xf "v${POLLY_VERSION}.tar.gz"
    - export POLLY_ROOT="`pwd`/polly-${POLLY_VERSION}"
    - export PATH="${POLLY_ROOT}/bin:${PATH}"
    # -- end
    # install cmake
    - CMAKE_VERSION="3.0.0-ios-universal"
    - wget "https://github.com/ruslo/CMake/archive/v${CMAKE_VERSION}.tar.gz"
    - openssl sha1 "v${CMAKE_VERSION}.tar.gz"
    - tar xf "v${CMAKE_VERSION}.tar.gz"
    - cd "CMake-${CMAKE_VERSION}"
    - build.py --install --toolchain default --config Release --fwd "CMAKE_USE_SYSTEM_CURL=YES"
    - export PATH="`pwd`/_install/default/bin:${PATH}"
    - cd ..
    # -- end
    # verify installed cmake
    - which cmake
    - cmake --version
    # -- end

script:
    - mkdir _builds
    - cd _builds
    # download all
    - cmake ..
    # if run generate again, no download needed
    - cmake ..
